version: "3.9"
services:
  database:
    image: postgres:latest
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 5432:5432
    networks:
      - mynet
    volumes: 
      # - db:/var/lib/postgresql/data
      - ./conf/database/v1.0.0.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 20s
      timeout: 20s
      retries: 5
      start_period: 210s 
  api:
    container_name: api
    image: golang:1.20
    build:
      dockerfile: go.Dockerfile
      context: .
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy
    networks:
      - mynet
    volumes:
      - './:/src'
networks:
  mynet:
    driver: bridge
      



 