db:
  postgres:
   user: "keith"
   db_name: "cinder"
   password: "vrvervfr"
   host: "localhost"
   port: "5432"
   sslmode: "disable"
app:
  port: "9000"
cmd: "docker run -dit --name astela -p 5432:5432 postgres -e POSTGRES_PASSWORD=password"